bot_bot:
  avs_links: |
    Ask <#224104675031384065> or <@109369346740015104>
    Links:
    http://avisynth.nl/index.php/Guides
    http://www.avs-plus.net/
  vs_links: |
    Ask <#224104675031384065> or <@137780880344088576>
    Links:
    http://www.vapoursynth.com/doc/
    https://kageru.moe/blog/encode/
    https://guide.encode.moe
    https://iamscum.wordpress.com/other-useful-stuff/encode-pack/
  yuuno_links: |
    Ask <#224104675031384065> or <@147060397881425920>
    Links:
    https://pypi.python.org/pypi/yuuno
    https://github.com/stuxcrystal/yuuno
    https://myanimelist.net/character/32939/Arashiko_Yuuno
  x264_links: |
    Ask <#224104675031384065> or <@109355116917743616>
    Links:
    https://encodingwissen.de/codecs/x264/referenz/
    https://en.wikibooks.org/wiki/MeGUI/x264_Settings
    http://x264.janhum.alfahosting.org/fullhelp.txt
    https://kageru.moe/blog/encode/
    https://guide.encode.moe
  ffmpeg_links: |
    Ask <#224104675031384065> or <@206853964405145600>
    Links:
    https://www.ffmpeg.org
    https://iamscum.wordpress.com/guides/hardsub-guide/
    https://thebombzen.com/articles/ffmpeg/index.html
  getnative_links: |
    Ask <#224104675031384065> or <@134750562062303232>
    Bot:
    You can test getnative with the bot.
    For more information use ">>getnative --help"
    
    Links:
    https://github.com/Infiziert90/getnative (standalone)
    https://ddl.kageru.moe/kbz12.pdf (WIP)
  member_join: |
    Welcome to our server.
    Please take your time to read all the info above.
    
    Willkommen auf unserem Server.
    Bitte nimm dir Zeit, um alle Info oben durchzulesen.
  command_overview: |
    __**English**__
    Make sure to give yourself a language group
    You'll get kicked after 30 minutes without being in one of the language groups

    If you want to see the following channels/categories, click on the corresponding emojis:
    #public_ger | :flag_de:
    #public_eng | :flag_gb:
    #public_jap | :flag_jp:

    "Fansub releated channels" | :white_flower:
    "NSFW" and "NSFL" | :underage:

    __**Deutsch**__
    Zuallererst musst du dir eine Sprachgruppe geben
    Du wirst nach 30 Minuten gekickt, wenn du in keiner der Sprachgruppen bist

    Wenn du die folgenden Channel/Kategorien sehen möchtest, klicke die entsprechenden Emojis an:
    #public_ger | :flag_de:
    #public_eng | :flag_gb:
    #public_jap | :flag_jp:

    "Fansub relatierte Channel" | :white_flower:
    "Channel für Community-Spiele" | :game_die:
    "NSFW" und "NSFL" | :underage:
  help_message: |
    __**Invite**__
    https://discord.gg/ZB7ZXbN
  welcome_note: |
    ```py
    @Note
    Link Preview needs to be activated, so that you can see the messages:
    "Settings -> Text & Images -> Link Preview"

    @Hinweis
    Die Linkvorschau muss aktiviert sein, um die Nachrichten zu sehen:
    "Einstellungen -> Text & Bilder -> Linksvorschau"
    ```
